### ISSUE TITLE
Tinyproxy hangs at some point

### ISSUE THREAD

**Issue by deriklogov** [tinyproxy/tinyproxy#383]
OS:  CentOS Linux release 8.3.2011
Issue: 
Tinyproxy stop proceeding any requests after working for couple days or week, depends on the load.
Config part:
MaxClients 500
BindSame yes

Reproduce error: 
We are running couple 4-5 Chrome browsers which are using 1 proxy (TinyProxy) server.

I am not 100% sure what would be the right way to track the issue , but i found a lot of those error in TinyProxy log file:

ERROR     Jun 24 15:32:10.195 [1311115]: read_request_line: Client (file descriptor: 19) closed socket before read.
ERROR     Jun 24 15:32:10.196 [1311115]: read_request_line: Client (file descriptor: 7) closed socket before read.
ERROR     Jun 24 15:32:10.196 [1311115]: read_request_line: Client (file descriptor: 13) closed socket before read.
ERROR     Jun 24 15:32:10.196 [1311115]: read_request_line: Client (file descriptor: 16) closed socket before read.
ERROR     Jun 24 15:32:10.196 [1311115]: read_request_line: Client (file descriptor: 10) closed socket before read.
ERROR     Jun 24 15:32:13.085 [1311115]: read_request_line: Client (file descriptor: 23) closed socket before read.
ERROR     Jun 24 15:32:13.088 [1311115]: Error reading readable client_fd 23
WARNING   Jun 24 15:32:13.088 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:32:20.435 [1311115]: read_request_line: Client (file descriptor: 31) closed socket before read.
ERROR     Jun 24 15:32:20.435 [1311115]: read_request_line: Client (file descriptor: 29) closed socket before read.
ERROR     Jun 24 15:32:20.435 [1311115]: read_request_line: Client (file descriptor: 25) closed socket before read.
ERROR     Jun 24 15:32:20.435 [1311115]: read_request_line: Client (file descriptor: 8) closed socket before read.
ERROR     Jun 24 15:32:21.011 [1311115]: Error reading readable client_fd 31
WARNING   Jun 24 15:32:21.015 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:32:21.012 [1311115]: read_request_line: Client (file descriptor: 231) closed socket before read.
ERROR     Jun 24 15:32:21.016 [1311115]: Error reading readable client_fd 231
WARNING   Jun 24 15:32:21.016 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:32:21.655 [1311115]: read_request_line: Client (file descriptor: 227) closed socket before read.
ERROR     Jun 24 15:32:21.669 [1311115]: Error reading readable client_fd 227
WARNING   Jun 24 15:32:21.693 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:32:30.675 [1311115]: read_request_line: Client (file descriptor: 10) closed socket before read.
ERROR     Jun 24 15:32:30.675 [1311115]: read_request_line: Client (file descriptor: 176) closed socket before read.
ERROR     Jun 24 15:32:30.675 [1311115]: read_request_line: Client (file descriptor: 19) closed socket before read.
ERROR     Jun 24 15:43:36.765 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:43:36.766 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:43:52.136 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:43:52.136 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:43:56.680 [1311115]: Error reading readable client_fd 7
WARNING   Jun 24 15:43:56.680 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:06.993 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:44:06.993 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:12.287 [1311115]: Error reading readable client_fd 7
WARNING   Jun 24 15:44:12.288 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:26.688 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:44:26.688 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:29.022 [1311115]: Error reading readable client_fd 7
WARNING   Jun 24 15:44:29.023 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:36.723 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:44:36.723 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:40.173 [1311115]: Error reading readable client_fd 7
WARNING   Jun 24 15:44:40.174 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:46.691 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:44:46.692 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:49.038 [1311115]: Error reading readable client_fd 8
WARNING   Jun 24 15:44:49.038 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:52.013 [1311115]: Error reading readable client_fd 7
WARNING   Jun 24 15:44:52.014 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:44:52.898 [1311115]: Error reading readable client_fd 9
WARNING   Jun 24 15:44:52.898 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:45:04.377 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:45:04.377 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:45:17.532 [1311115]: Error reading readable client_fd 6
WARNING   Jun 24 15:45:17.532 [1311115]: Could not retrieve request entity
ERROR     Jun 24 15:45:17.643 [1311115]: Error reading readable client_fd 7
WARNING   Jun 24 15:45:17.643 [1311115]: Could not retrieve request entity

So the only solution right now is to restart tinyproxy service after this happens.
I would really appreciate if you can point me how to track/solve this issue.
Thank You

**Comment by rofl0r** [comment]
use tinyproxy 1.11.0

**Comment by deriklogov** [comment]
How do i check what is my version 
and what is the proper way to upgrade ?

**Comment by deriklogov** [comment]
We have
tinyproxy 1.11.0-rc1-23-git-11a4f6c
installed on our server.

**Comment by rofl0r** [comment]
is 1311115 the pid of the process ?

next time the process gets into unusable state, may it could help to look at the files in its /proc/pid to gather some information, like how many file descriptors are open and so on.
i'd recommend to use latest version anyhow so we dont waste our time debugging something that could already be fixed.

**Comment by deriklogov** [comment]
Yes, we are using latest version, i double checked that
I am waiting right now to hang again, and then i will take a closer look what the proxy responds with and if /proc/pid could get any info. 
How do i check how many file descriptors are open ?
and what else i would need to check with /proc/pid ?

I also noticed that tinyproxy can not be restart with service tinyproxy restart command, this brings tinyproxy to status "loaded" and can not find PID file. It seems like its trying to do restart too fast, so the slower way of restarting by stop and then start seems like the fix to it.

**Comment by deriklogov** [comment]
in the current working condition this is what i am getting with file descriptors:
cd /proc/1378006/fd
[root@localhost fd]# ls -l | wc -l
305
[root@localhost fd]# lsof | wc -l
178094

i will check what does it says when it hangs

**Comment by deriklogov** [comment]
its still working since i i run it yesterday, but looks like number of file descriptors going up:
Yesterday:
[root@localhost fd]# lsof | wc -l
178094

Today in a morning:
[centos@localhost fd]$ lsof | wc -l
182594


Right now:
[centos@localhost fd]$ lsof | wc -l
287996

**Comment by rofl0r** [comment]
> Is this normal ? Or its something that might create this issue ?

it might be another process that doesn't properly clean-up used resources. maybe you can wire up a script that parses lsof output and adds a per-pid count, so you can check which process is doing this (and what the resources in question are)

**Comment by deriklogov** [comment]
this count goes per pid of tinyproxy ,
so i found tinyproxy process by:

[centos@localhost ~]$ ps aux | grep tinyproxy
nobody   1378006  0.6  0.1 4271692 22704 ?       Sl   Jun24   8:48 /usr/local/bin/tinyproxy -c /usr/local/etc/tinyproxy/tinyproxy.conf
which is run by "nobody" , i guess its run by service thats why its nobody.

and then i trace down process ID 1378006
by going into 
cd /proc/1378006/fd
and then i count all those file descriptors , and that number keeps going up
sudo lsof | wc -l
292664

all of those belongs to same PID (1378006) with owner of "tinyproxy" , so it seems like something does not clean them up for
some reason, not sure why

**Comment by rofl0r** [comment]
> and then i count all those file descriptors , and that number keeps going up
> sudo lsof | wc -l

lsof lists open files for *all* processes, and its behaviour isnt affected by the current directory you're in.

if you're in tinyproxy's /proc/$pid/fd directory, `ls -1` lists the number of file descriptors it has open.

**Comment by deriklogov** [comment]
I found script to count them, so that tinyproxy process using 
1378006 733
733 file descriptors
I am not sure if its a lot, i guess have to wait until it hangs again

**Comment by rofl0r** [comment]
> We are running couple 4-5 Chrome browsers which are using 1 proxy (TinyProxy) server.

do you ever close those ? it's possible each chrome user has dozens of tabs open which keep persistent websocket connections

> I found script to count them, so that tinyproxy process using

why not just do `ls -1 | wc -l` in /proc/$pid/fd  of tinyproxy process ?

**Comment by pauldraper** [comment]
I have encountered this regularly.

My workaround is to tweak systemd

```
[Service]
Restart=on-failure
RuntimeMaxSec=4h
```

**Comment by rofl0r** [comment]
@deriklogov could you try again with master and paste log when this happens again? i added some improved error output that might help tracking down the cause.

**Comment by deriklogov** [comment]
> 
> 
> @deriklogov could you try again with master and paste log when this happens again? i added some improved error output that might help tracking down the cause.

How do i update the master file ?

**Comment by rofl0r** [comment]
```
git clone https://github.com/tinyproxy/tinyproxy
cd tinyproxy
```
then follow the build instructions in README

**Comment by laurentgoudet** [comment]
I can confirm I am experiencing that as well after upgrading to `1.11.0-1`, although downgrading to `1.10.0-5` fixes the issue, i.e. it seems to be a regression.

When that happens, I have the following logs:

```
ERROR     Feb 24 09:47:13.295 [7001]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 24 09:47:21.488 [7001]: opensock: Could not establish a connection to app_base_url:7766
INFO      Feb 24 09:47:24.498 [7001]: Closed connection between local client (fd:26) and remote client (fd:30)
ERROR     Feb 24 09:47:25.584 [7001]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 24 09:48:06.544 [7001]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 24 09:48:06.544 [7001]: opensock: Could not establish a connection to app_base_url:7766
INFO      Feb 24 09:48:23.245 [7001]: Closed connection between local client (fd:7) and remote client (fd:9)
CONNECT   Feb 24 09:48:23.268 [7001]: Connect (file descriptor 3): 127.0.0.1
CONNECT   Feb 24 09:48:23.270 [7001]: Request (file descriptor 3): GET /components/thumbnail-viewer/group-scrolling?story_only=true&fln-cache-bust=1645696103141&no_abtest=true&image-optimizer=bypass HTTP/1.1
```

Here `tinyproxy` got stuck for ~1 minute. While this was happening, I was running `curl http://app_base_url:7766 -D - -o /dev/null -s` in another terminal every second (`app_base_url` is defined is `/etc/hosts`) & the connection was fine.

I occasionally see some other issues as well, e.g.:

```
ERROR     Feb 24 09:44:54.973 [7001]: read_buffer: read() failed on fd 27: Connection reset by peer
```

Those don't cause `tinyproxy` to get stuck, but still cause the requests to fail.

Downgrading to `1.10.0-5` makes all those issues go away, which is the workaround I am using for now since that version is still available on the upstream PPA.

**Comment by rofl0r** [comment]
i think this issue is now fixed in master, would you mind trying it, @laurentgoudet ?

**Comment by laurentgoudet** [comment]
> i think this issue is now fixed in master, would you mind trying it, @laurentgoudet ?

Hm I've compiled & tested `1.11.0-rc1-52-git-9718be0`, and the issue remains, same symptoms, i.e. the upstream connection drops & takes a long time to recover, with the following logs:

```
ERROR     Feb 25 08:43:48.929 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:43:53.025 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:43:53.027 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:43:53.027 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:43:57.120 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:43:57.121 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:44:01.216 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:44:01.216 [28613]: opensock: Could not establish a connection to app_base_url:7766
ERROR     Feb 25 08:44:01.216 [28613]: opensock: Could not establish a connection to app_base_url:7766
```

**Comment by rofl0r** [comment]
thanks for testing.

> Hm I've compiled & tested 1.11.0-rc1-52-git-9718be0, and the issue remains, same symptoms, i.e. the upstream connection drops & takes a long time to recover

could this be due to a very high timeout value in your config ?

**Comment by finnje** [comment]
I'm seeing the same thing as @laurentgoudet where a downgrade to 1.10.0 resolves the errors.

**Comment by rofl0r** [comment]
@finnje would you mind posting your config, and which OS you use so i can try to reproduce this?
also if you feel adventurous you might want to try to `git bisect` the commit history between master and 1.10.0.

**Comment by rofl0r** [comment]
ok, i've studied the error messages above and the error might be due to read_request_line failing due to closed socket, and then trying to send an HTTP error to the closed socket (which might block indefinitely ?)


please confirm whether this patch fixes the issue:

```diff
diff --git a/src/reqs.c b/src/reqs.c
index 50f6914..2453415 100644
--- a/src/reqs.c
+++ b/src/reqs.c
@@ -1628,11 +1628,7 @@ void handle_connection (struct conn_s *connptr, union sockaddr_union* addr)
 
         if (read_request_line (connptr) < 0) {
                 update_stats (STAT_BADCONN);
-                indicate_http_error (connptr, 408, "Timeout",
-                                     "detail",
-                                     "Server timeout waiting for the HTTP request "
-                                     "from the client.", NULL);
-                HC_FAIL();
+                goto done;
         }
 
         /*
```

**Comment by finnje** [comment]
That fix does appear to clear up the errors I was seeing.

**Comment by rofl0r** [comment]
> That fix does appear to clear up the errors I was seeing.

thanks for feedback. does it also fix the hanging, though ?

**Comment by finnje** [comment]
It appears to have resolved the hanging as well.  I don't see a single error on my stats page.

**Comment by rofl0r** [comment]
well, this codepath is only triggered when the client prematurely closes the connection, due to whatever. since there's still `update_stats (STAT_BADCONN);` above the changed code, the path is only entered when you also (supposedly, unless the code is bugged too) see bad connections in the stats page.

**Comment by finnje** [comment]
> 

I was running alpine in docker with the latest tinyproxy installed.  Use this image [docker.io/kalaksi/tinyproxy](docker.io/kalaksi/tinyproxy) and simply change the `ALLOWED_NETWORKS` to your network in the **docker-compose.yml**.  For the change above I complied on ubuntu 20.04.

**Comment by rofl0r** [comment]
that link doesn't work

**Comment by finnje** [comment]
Sorry wasn't supposed to have the "https://" on the front.  Link to repo is here [https://github.com/kalaksi/docker-tinyproxy](https://github.com/kalaksi/docker-tinyproxy)

**Comment by rofl0r** [comment]
i pushed the potential fix to master, leaving this open until it's confirmed as resolved.

**Comment by ibukanov-zscaler** [comment]
I observed an issue that looks like this even with tinyproxy compiled from the tip of the main branch or the last release 1.11.1 or 1.11.0. Basically in Chromium opening at the same time 10 tabs that loads a lot of resources triggers partial load of pages with a few ERROR entries in the tinyproxy log like `read_request_line: Client (file descriptor: 19) closed socket before read.`. Downgrading to 1.10.0 solved this.

**Comment by rofl0r** [comment]
tp 1.11 is much faster because it doesnt lookup reverse dns for each incoming connection, so what you're experiencing could simply be the remote server being overwhelmed by too many parallel requests. at least in firefox you can mitigate this by setting maximum connections to a lower value in about:config, i suspect chrome has similar options.

**Comment by ibukanov-zscaler** [comment]
For us the direct connection or using squid proxy makes things work. With tinyproxy running on the same localhost there is an issue. Here we are talking about single Chrome client that opens 10+ tabs at the same time using the bookmark menu. Granted our networking setup is rather unusual, but still Chromium works with the direct connection.

**Comment by ibukanov-zscaler** [comment]
@rofl0r Thanks for the tip about changing the connection limit. Setting [MaxConnectionsPerProxy](https://chromeenterprise.google/policies/?policy=MaxConnectionsPerProxy) to 99, the maximum supported by Chromium, resolved the issue in our case. It is puzzling that the issue was a too low limit, not too high.

**Comment by rofl0r** [comment]
ok, maybe you can use `strace -f` on the tinyproxy process and find out what's causing the sockets to return <= 0 on read

**Comment by younsl** [comment]
I hope my solution helps everyone here. I faced frequent hangs with tinyproxy `1.8.3` on an amd64-based EC2 instance, causing 'NLB - TargetGroup - UnHealthy Host Count' errors every 5-7 days, requiring manual reboots. Doubling the instance size didn't help, but after [the maintainer mentioned using version `1.11.x`](https://github.com/tinyproxy/tinyproxy/issues/383#issuecomment-1887250882), **I upgraded tinyproxy from `1.8.3` to `1.11.2`**. It's now been stable for over 14 days without reboots. For upgrade steps, check [this article](https://stackoverflow.com/a/71725685/27404655).
